export const USERROLE: any[] = [
  {
    options: [
      { label: 'Administrator', value: 'Admin' },
      { label: 'Engineer', value: 'Engineer' },
      { label: 'Clinician', value: 'Clinician' },
      { label: 'External Service Provider', value: 'ESP' },
    ],
  },
];

export const NEWUSERROLE:any[]=[
  {
    options:[
      { label: 'Engineer', value: 'Engineer' },
      { label: 'External Service Provider', value: 'ESP' },
    ]
  }
]

export const REGIONS = [
  {
    options: [
      { label: 'Ashanti', value: 'Ashanti' },
      { label: 'Greater Accra', value: 'Greater Accra' },
      { label: 'Bono', value: 'Bono' },
      { label: 'Bono East', value: 'Bono East' },
      { label: 'Central', value: 'Central' },
      { label: 'Ahafo', value: 'Ahafo' },
      { label: 'Eastern', value: 'Eastern' },
      { label: 'Northern', value: 'Northern' },
      { label: 'Savannah', value: 'Savannah' },
      { label: 'North East', value: 'North East' },
      { label: 'Upper East', value: 'Upper East' },
      { label: 'Upper West', value: 'Upper West' },
      { label: 'Volta', value: 'Volta' },
      { label: 'Oti', value: 'Oti' },
      { label: 'Western', value: 'Western' },
      { label: 'Western North', value: 'Western North' },
    ],
  },
];

export const COUNTRY: any[] = [
  {
    options: [
      { label: 'Afghanistan', value: 'Afghanistan' },
      { label: 'Albania', value: 'Albania' },
      { label: 'Algeria', value: 'Algeria' },
      { label: 'Andorra', value: 'Andorra' },
      { label: 'Angola', value: 'Angola' },
      { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
      { label: 'Argentina', value: 'Argentina' },
      { label: 'Armenia', value: 'Armenia' },
      { label: 'Australia', value: 'Australia' },
      { label: 'Austria', value: 'Austria' },
      { label: 'Azerbaijan', value: 'Azerbaijan' },
      { label: 'The Bahamas', value: 'The Bahamas' },
      { label: 'Bahrain', value: 'Bahrain' },
      { label: 'Bangladesh', value: 'Bangladesh' },
      { label: 'Barbados', value: 'Barbados' },
      { label: 'Belarus', value: 'Belarus' },
      { label: 'Belgium', value: 'Belgium' },
      { label: 'Belize', value: 'Belize' },
      { label: 'Benin', value: 'Benin' },
      { label: 'Bolivia', value: 'Bolivia' },
      { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
      { label: 'Botswana', value: 'Botswana' },
      { label: 'Brazil', value: 'Brazil' },
      { label: 'Brunei', value: 'Brunei' },
      { label: 'Brunswick and Lüneburg', value: 'Brunswick and Lüneburg' },
      { label: 'Bulgaria', value: 'Bulgaria' },
      { label: 'Burkina Faso', value: 'Burkina Faso' },
      { label: 'Burma', value: 'Burma' },
      { label: 'Burundi', value: 'Burundi' },
      { label: 'Cabo Verde', value: 'Cabo Verde' },
      { label: 'Cambodia', value: 'Cambodia' },
      { label: 'Cameroon', value: 'Cameroon' },
      { label: 'Canada', value: 'Canada' },
      { label: 'The Cayman Islands', value: 'The Cayman Islands' },
      { label: 'Central African Republic', value: 'Central African Republic' },
      { label: 'Chad', value: 'Chad' },
      { label: 'Chile', value: 'Chile' },
      { label: 'China', value: 'China' },
      { label: 'Colombia', value: 'Colombia' },
      { label: 'Comoros', value: 'Comoros' },
      { label: 'Costa Rica', value: 'Costa Rica' },
      { label: 'Cote d`Ivoire', value: 'Cote d`Ivoire' },
      { label: 'Croatia', value: 'Croatia' },
      { label: 'Cuba', value: 'Cuba' },
      { label: 'Cyprus', value: 'Cyprus' },
      { label: 'Czechia', value: 'Czechia' },
      { label: 'Czechoslovakia', value: 'Czechoslovakia' },
      {
        label: 'Democratic Republic of the Congo',
        value: 'Democratic Republic of the Congo',
      },
      { label: 'Denmark', value: 'Denmark' },
      { label: 'Djibouti', value: 'Djibouti' },
      { label: 'Dominica', value: 'Dominica' },
      { label: 'Ecuador', value: 'Ecuador' },
      { label: 'Egypt', value: 'Egypt' },
      { label: 'El Salvador', value: 'El Salvador' },
      { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
      { label: 'Eritrea', value: 'Eritrea' },
      { label: 'Estonia', value: 'Estonia' },
      { label: 'Eswatini', value: 'Eswatini' },
      { label: 'Ethiopia', value: 'Ethiopia' },
      { label: 'Fiji', value: 'Fiji' },
      { label: 'Finland', value: 'Finland' },
      { label: 'France', value: 'France' },
      { label: 'Gabon', value: 'Gabon' },
      { label: 'The Gambia', value: 'The Gambia' },
      { label: 'Georgia', value: 'Georgia' },
      { label: 'Germany', value: 'Germany' },
      { label: 'Ghana', value: 'Ghana' },
      { label: 'Greece', value: 'Greece' },
      { label: 'Grenada', value: 'Grenada' },
      { label: 'Guatemala', value: 'Guatemala' },
      { label: 'Guinea', value: 'Guinea' },
      { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
      { label: 'Guyana', value: 'Guyana' },
      { label: 'Haiti', value: 'Haiti' },
      { label: 'Honduras', value: 'Honduras' },
      { label: 'Hungary', value: 'Hungary' },
      { label: 'Iceland', value: 'Iceland' },
      { label: 'India', value: 'India' },
      { label: 'Indonesia', value: 'Indonesia' },
      { label: 'Iran', value: 'Iran' },
      { label: 'Iraq', value: 'Iraq' },
      { label: 'Ireland', value: 'Ireland' },
      { label: 'Israel', value: 'Israel' },
      { label: 'Italy', value: 'Italy' },
      { label: 'Jamaica', value: 'Jamaica' },
      { label: 'Japan', value: 'Japan' },
      { label: 'Jordan', value: 'Jordan' },
      { label: 'Kazakhstan', value: 'Kazakhstan' },
      { label: 'Kenya', value: 'Kenya' },
      { label: 'Serbia', value: 'Serbia' },
      { label: 'Kiribati', value: 'Kiribati' },
      { label: 'Korea', value: 'Korea' },
      { label: 'Kosovo', value: 'Kosovo' },
      { label: 'Kuwait', value: 'Kuwait' },
      { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
      { label: 'Laos', value: 'Laos' },
      { label: 'Latvia', value: 'Latvia' },
      { label: 'Lebanon', value: 'Lebanon' },
      { label: 'Lesotho', value: 'Lesotho' },
      { label: 'Liberia', value: 'Liberia' },
      { label: 'Libya', value: 'Cyprus' },
      { label: 'Liechtenstein', value: 'Liechtenstein' },
      { label: 'Lithuania', value: 'Lithuania' },
      { label: 'Luxembourg', value: 'Luxembourg' },
      { label: 'Madagascar', value: 'Madagascar' },
      { label: 'Malawi', value: 'Malawi' },
      { label: 'Malaysia', value: 'Malaysia' },
      { label: 'Maldives', value: 'Maldives' },
      { label: 'Mali', value: 'Mali' },
      { label: 'Malta', value: 'Malta' },
      { label: 'Marshall Islands', value: 'Marshall Islands' },
      { label: 'Mauritania', value: 'Mauritania' },
      { label: 'Mauritius', value: 'Mauritius' },
      { label: 'Mexico', value: 'Mexico' },
      { label: 'Micronesia', value: 'Micronesia' },
      { label: 'Moldova', value: 'Moldova' },
      { label: 'Monaco', value: 'Monaco' },
      { label: 'Mongolia', value: 'Mongolia' },
      { label: 'Montenegro', value: 'Montenegro' },
      { label: 'Morocco', value: 'Morocco' },
      { label: 'Mozambique', value: 'Mozambique' },
      { label: 'Namibia', value: 'Namibia' },
      { label: 'Nauru', value: 'Nauru' },
      { label: 'Nepal', value: 'Nepal' },
      { label: 'The Netherlands', value: 'The Netherlands' },
      { label: 'New Zealand', value: 'New Zealand' },
      { label: 'Nicaragua', value: 'Nicaragua' },
      { label: 'Niger', value: 'Niger' },
      { label: 'Nigeria', value: 'Nigeria' },
      { label: 'North Macedonia', value: 'North Macedonia' },
      { label: 'Norway', value: 'Norway' },
      { label: 'Oman', value: 'Oman' },
      { label: 'Pakistan', value: 'Pakistan' },
      { label: 'Palau', value: 'Palau' },
      { label: 'Panama', value: 'Panama' },
      { label: 'Paraguay', value: 'Paraguay' },
      { label: 'Peru', value: 'Peru' },
      { label: 'Philippines', value: 'Philippines' },
      { label: 'Poland', value: 'Poland' },
      { label: 'Portugal', value: 'Portugal' },
      { label: 'Qatar', value: 'Qatar' },
      { label: 'South Korea', value: 'South Korea' },
      { label: 'Republic of the Congo', value: 'Republic of the Congo' },
      { label: 'Romania', value: 'Romania' },
      { label: 'Russia', value: 'Russia' },
      { label: 'Rwanda', value: 'Rwanda' },
      { label: 'Samoa', value: 'Samoa' },
      { label: 'San Marino', value: 'San Marino' },
      { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
      { label: 'Saudi Arabia', value: 'Saudi Arabia' },
      { label: 'Senegal', value: 'Senegal' },
      { label: 'Seychelles', value: 'Seychelles' },
      { label: 'Sierra Leone', value: 'Sierra Leone' },
      { label: 'Singapore', value: 'Singapore' },
      { label: 'Slovakia', value: 'Slovakia' },
      { label: 'Slovenia', value: 'Slovenia' },
      { label: 'Somalia', value: 'Somalia' },
      { label: 'South Africa', value: 'South Africa' },
      { label: 'South Sudan', value: 'South Sudan' },
      { label: 'Spain', value: 'Spain' },
      { label: 'Sri Lanka', value: 'Sri Lanka' },
      { label: 'Sudan', value: 'Sudan' },
      { label: 'Suriname', value: 'Suriname' },
      { label: 'Sweden', value: 'Sweden' },
      { label: 'Switzerland', value: 'Switzerland' },
      { label: 'Syria', value: 'Syria' },
      { label: 'Tajikistan', value: 'Tajikistan' },
      { label: 'Tanzania', value: 'Tanzania' },
      { label: 'Thailand', value: 'Thailand' },
      { label: 'Togo', value: 'Togo' },
      { label: 'Tonga', value: 'Tonga' },
      { label: 'Tunisia', value: 'Tunisia' },
      { label: 'Turkey', value: 'Turkey' },
      { label: 'Turkmenistan', value: 'Turkmenistan' },
      { label: 'Tuvalu', value: 'Tuvalu' },
      { label: 'Uganda', value: 'Uganda' },
      { label: 'Ukraine', value: 'Ukraine' },
      { label: 'United States of America', value: 'United States of America' },
      { label: 'The United Arab Emirates', value: 'The United Arab Emirates' },
      { label: 'The United Kingdom', value: 'The United Kingdom' },
      { label: 'Uruguay', value: 'Uruguay' },
      { label: 'Uzbekistan', value: 'Uzbekistan' },
      { label: 'Vanuatu', value: 'Vanuatu' },
      { label: 'Venezuela', value: 'Venezuela' },
      { label: 'Vietnam', value: 'Vietnam' },
      { label: 'Yemen', value: 'Yemen' },
      { label: 'Zambia', value: 'Zambia' },
      { label: 'Zimbabwe', value: 'Zimbabwe' },
    ],
  },
];
